trigger:
- v2

pool:
  vmImage: 'macOS-10.13'

steps:
- task: Gradle@2
  displayName: Build devDebug
  inputs:
    workingDirectory: 'android'
    gradleWrapperFile: 'android/gradlew'
    gradleOptions: '-Xmx3072m'
    tasks: 'assembleDevDebug'