trigger:
- v2

pool:
  vmImage: 'macOS-10.13'

steps:
- task: DownloadSecureFile@1
  displayName: Fetch google-services.json
  inputs:
    secureFile: 'google-services.json'
- task: CopyFiles@2
  displayName: Install google-services.json
  inputs:
    sourceFolder: '$(Agent.TempDirectory)'
    contents: 'google-services.json'
    targetFolder: 'android/app'
- task: Gradle@2
  displayName: Build devDebug
  inputs:
    workingDirectory: 'android'
    gradleWrapperFile: 'android/gradlew'
    gradleOptions: '-Xmx3072m'
    tasks: 'assembleDevDebug'