trigger:
  branches:
    include:
      - v2
  paths:
    include:
      - .azure/*
      - android/*

pool:
  vmImage: 'macOS-10.13'

steps:
- task: DownloadSecureFile@1
  displayName: Fetch google-services.json
  inputs:
    secureFile: 'google-services.json'
- task: CopyFiles@2
  displayName: Install google-services.json
  inputs:
    sourceFolder: '$(Agent.TempDirectory)'
    contents: 'google-services.json'
    targetFolder: 'android/app'
- task: Gradle@2
  displayName: checkstyle
  inputs:
    workingDirectory: 'android'
    gradleWrapperFile: 'android/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    tasks: 'checkstyle --info'
- task: Gradle@2
  displayName: pmd
  inputs:
    workingDirectory: 'android'
    gradleWrapperFile: 'android/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    tasks: 'pmd --info'
- task: Gradle@2
  displayName: Build devDebug
  inputs:
    workingDirectory: 'android'
    gradleWrapperFile: 'android/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    tasks: 'assembleDevDebug'
- task: Gradle@2
  displayName: findbugs
  inputs:
    workingDirectory: 'android'
    gradleWrapperFile: 'android/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    tasks: 'findbugs --info'
- task: Gradle@2
  displayName: Run tests
  inputs:
    workingDirectory: 'android'
    gradleWrapperFile: 'android/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'testDevDebug'
- task: CopyFiles@2
  displayName: Stage reports for publishing
  inputs:
    contents: '**/reports/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true
- task: PublishBuildArtifacts@1
  displayName: Publish reports
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Reports
- task: Bash@3
  displayName: Rename devDebug APK
  inputs:
    targetType: inline
    workingDirectory: 'android/app/build/outputs/apk/dev/debug'
    script: mv app-dev-debug.apk zephyr-dev-debug-$(Build.BuildNumber).apk
- task: CopyFiles@2
  displayName: Stage devDebug APK for publishing
  inputs:
    contents: 'android/app/build/outputs/apk/dev/debug/*.apk'
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true
    flattenFolders: true
- task: PublishBuildArtifacts@1
  displayName: Publish devDebug APK
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: APK