# Zephyr Desktop build pipeline
# Executes for commits to `v2` branch.

trigger:
  branches:
    include:
      - v2
  paths:
    include:
      - .azure/*
      - desktop/*

pr: none

variables:
  - group: zephyr-desktop

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: PowerShell@2
  displayName: Install dependencies
  inputs:
    targetType: 'inline'
    script: 'yarn'
    workingDirectory: 'desktop'
- task: PowerShell@2
  displayName: Run tests
  inputs:
    targetType: 'inline'
    script: 'yarn test'
    workingDirectory: 'desktop'
- task: PublishTestResults@2
  displayName: Publish test results
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: 'desktop/TEST-jest_junit.xml'
- task: PowerShell@2
  displayName: Build Zephyr Desktop (prod)
  inputs:
    targetType: 'inline'
    script: 'yarn dist-prod'
    workingDirectory: 'desktop'
- task: CopyFiles@2
  displayName: Stage test report for publishing
  condition: always()
  inputs:
    contents: 'desktop/*.xml'
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true
- task: PublishBuildArtifacts@1
  displayName: Publish test report
  condition: always()
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Test report
- task: CopyFiles@2
  displayName: Stage desktop artifact for publishing
  condition: always()
  inputs:
    contents: 'desktop/dist/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true
- task: PublishBuildArtifacts@1
  displayName: Publish desktop artifact
  condition: always()
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Zephyr Desktop