# Zephyr Desktop PR build pipeline
# Executes for PRs into the `v2` branch.

name: $(Date:yyyyMMdd)$(Rev:rr)

pr:
  branches:
    include:
    - v2
  paths:
    include:
      - .azure/desktop.yml
      - desktop/*
    exclude:
      - desktop/README.md

trigger: none

variables:
  - group: zephyr-desktop

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NodeTool@0
  displayName: Setup NodeJS
  inputs:
    versionSpec: '10.9.0' 
- task: PowerShell@2
  displayName: Install dependencies
  inputs:
    targetType: 'inline'
    script: 'yarn'
    workingDirectory: 'desktop'
- task: PowerShell@2
  displayName: Run tests
  inputs:
    targetType: 'inline'
    script: 'yarn test'
    workingDirectory: 'desktop'
- task: PublishTestResults@2
  displayName: Publish test results
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: 'desktop/TEST-jest_junit.xml'
- task: PowerShell@2
  displayName: Build Zephyr Desktop - Steam
  inputs:
    targetType: 'inline'
    script: 'yarn dist-steam'
    workingDirectory: 'desktop'
- task: CopyFiles@2
  displayName: Stage test report for publishing
  condition: always()
  inputs:
    contents: 'desktop/*.xml'
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true
- task: PublishBuildArtifacts@1
  displayName: Publish test report
  condition: always()
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Test report
- task: CopyFiles@2
  displayName: Stage Zephyr Desktop - Steam for publishing
  condition: always()
  inputs:
    sourceFolder: 'desktop/dist/win-unpacked'
    contents: '**/*'
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true
- task: PublishBuildArtifacts@1
  displayName: Publish desktop artifact
  condition: always()
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Zephyr Desktop - Steam